#! /usr/bin/env python
#
# guideview -- Customized Ginga viewer for Gen2 guider operation.
#
import sys
import os
from argparse import ArgumentParser

# NOTE: need to set here so that ginga.util.paths picks it up first
os.environ['GINGA_HOME'] = os.path.join(os.environ['CONFHOME'], 'guideview')

from ginga.rv import main as g_main
from ginga.misc.Bunch import Bunch

import fitsview.plugins

default_layout = ['seq', {},
                   ['vbox', dict(name='top', width=1900, height=1300),
                    ['ws', dict(wstype='stack', stretch=0, name='menubar',
                                group=99)],
                    ['hpanel', dict(stretch=1),
                     ['ws', dict(name='left', width=300, stretch=0),
                      # (tabname, layout), ...
                      [("Info", ['vpanel', {},
                                 ['ws', dict(name='uleft', height=300,
                                             show_tabs=False, group=3)],
                                 ['ws', dict(name='lleft', height=430,
                                             show_tabs=True, group=3)],
                                 ]
                        )]
                      ],
                     ['vpanel', dict(width=1600, stretch=1),
                      ['hpanel', dict(height=600),
                       ['vbox', dict(name='main', width=800),
                        ['ws', dict(name='channels', group=1, stretch=1)],
                        ['ws', dict(wstype='stack', stretch=0, name='cbar',
                                    group=99)],
                        ['ws', dict(wstype='stack', stretch=0, name='readout',
                                    group=99)],
                        ['ws', dict(wstype='stack', stretch=0, name='operations',
                                    group=99)],
                        ],
                       ['ws', dict(name='right', width=800, group=2),
                        # (tabname, layout), ...
                        [("Dialogs", ['ws', dict(name='dialogs', group=2)
                                      ]
                          )]
                        ],
                       ],
                      ['hpanel', dict(height=600),
                       ['ws', dict(name='sub1', width=800, height=420,
                                   group=1)],
                       ['ws', dict(name='sub2', width=800, group=1)],
                       ],
                      ],
                     ],
                    ['ws', dict(name='toolbar', height=40, stretch=0,
                                show_tabs=False, group=2)],
                    ['hbox', dict(name='status', stretch=0)],
                   ]]


def get_plugin_spec(name):
    l_name = name.lower()
    for spec in g_main.plugins:
        if spec.module.lower() == l_name:
            return spec
    return KeyError(name)

def remove_plugin_spec(name):
    l_name = name.lower()
    for spec in g_main.plugins:
        if spec.module.lower() == l_name:
            g_main.plugins.remove(spec)
            return
    return KeyError(name)

def add_plugin_spec(spec):
    g_main.plugins.append(spec)


default_channels = [('AG', 'channels'), ('SV', 'sub1'), ('HSCSCAG', 'sub1'),
                    ('QDAS_VGW', 'sub2'), ('DSS', 'sub2'),
                    ('SH', 'channels'),
                    ('HSCSHAG', 'channels'), ('HSCSH', 'channels'),
                    ('PFS', 'channels'),
                    ]
# default_channels = []


if __name__ == "__main__":
    # Tweak the sys.path here if you are loading plugins from some
    # area outside your PYTHONPATH
    pluginHome = os.path.split(sys.modules['fitsview.plugins'].__file__)[0]
    sys.path.insert(0, pluginHome)

    # change spec of stock Header plugin to start automatically, and don't
    # show icon in Operations plugin
    spec = get_plugin_spec('header')
    spec.start = True
    spec.optray = False

    # Subaru-specific plugins
    for spec in [
        Bunch(module='Gen2Int', ptype='global', hidden=True, optray=False,
              start=True, enabled=True),
        Bunch(module='VGW', hidden=True, ptype='global', optray=False,
              start=True, enabled=True),

        Bunch(module='Region_Selection', workspace='dialogs', ptype='local',
              hidden=True, enabled=True),
        Bunch(module='Sv_Drive', workspace='dialogs', ptype='local', hidden=True,
              enabled=True),
        Bunch(module='AgAutoSelect', workspace='dialogs', ptype='local', hidden=True,
              enabled=True),
        Bunch(module='AgAreaSelection', workspace='dialogs', ptype='local',
              hidden=True, enabled=True),
        Bunch(module='PFS_AG', workspace='dialogs', ptype='global', start=False,
              category='Subaru', enabled=True),
        Bunch(module='PFS_Focus', workspace='sub2', ptype='local',
              category='Subaru', enabled=True),
        ]:
        add_plugin_spec(spec)

    # construct viewer builder
    viewer = g_main.ReferenceViewer(layout=default_layout,
                                    appname="Guideview")
    viewer.add_default_plugins(except_global=['WCSMatch', 'RC', 'SAMP',
                                              'Thumbs', 'Blink',
                                              #'Contents', 'FBrowser'
                                             ],
                               except_local=['TVMark', 'TVMask',
                                             'ChangeHistory', 'Mosaic',
                                             'Blink', 'Compose',
                                             'PlotTable', 'Catalogs',
                                             #'FBrowser'
                                             ])
    #viewer.add_separately_distributed_plugins()
    viewer.channels = default_channels

    argprs = ArgumentParser()
    viewer.add_default_options(argprs)

    (options, args) = argprs.parse_known_args(sys.argv[1:])

    if options.display:
        os.environ['DISPLAY'] = options.display

    viewer.main(options, args)
